services:
  - type: web
    name: llm-product-categorizer
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: llm-product-categorizer-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: llm-product-categorizer-db
    databaseName: llm_product_categorizer
    user: llm_product_categorizer_user